### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by aarvndhNG** [skywhale-zhi/WeaponPlusCostCoin#1]
Can you make a English version

**Comment by skywhale-zhi** [comment]
My English is not very good. I guess I can only do machine translation. Which plug-in do you need to make English

**Comment by aarvndhNG** [comment]
Ok can I get your discord tag

**Comment by aarvndhNG** [comment]
> 

I can

**Comment by aarvndhNG** [comment]
@skywhale-zhi

**Comment by skywhale-zhi** [comment]
I'm already writing the English version.I don't have discord tag

**Comment by aarvndhNG** [comment]
Ok can you help me to make a plugin please

**Comment by skywhale-zhi** [comment]
The new version is ready

**Comment by aarvndhNG** [comment]
Thank anyways can you help me to make a plugin

**Comment by aarvndhNG** [comment]
I having in /plus command it's crashing my server

**Comment by skywhale-zhi** [comment]
are you pe?

**Comment by aarvndhNG** [comment]
Wdym

**Comment by skywhale-zhi** [comment]
Is your server or client a mobile phone? Not a computer.

**Comment by aarvndhNG** [comment]
Yes my server and I am running on my server on a site called failxnodes

**Comment by skywhale-zhi** [comment]
I guess too many words in the instruction caused the crash. I tested it locally with the computer Windows system without any problems.I didn't test the mobile phone. Is your server a Linux system?

**Comment by aarvndhNG** [comment]
Idk

**Comment by aarvndhNG** [comment]
@skywhale-zhi can you please help me please

**Comment by skywhale-zhi** [comment]
Is there an error log, or did you enter any instructions that caused the crash?

**Comment by aarvndhNG** [comment]
No

**Comment by aarvndhNG** [comment]
Can you help me please sir

**Comment by skywhale-zhi** [comment]
The key is that I don't know the reason for your error, nor can I reproduce the error here, nor do I know what system you use to run tshock

**Comment by skywhale-zhi** [comment]
Can you send me the system or platform or website of your open service

**Comment by aarvndhNG** [comment]
Failxnodes
